name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: yarn run format:check
      - run: yarn run test -- --coverage
        env: 
          CI: true
        if: github.event_name == 'push'
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain healthy-power.surge.sh
        env: 
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}